# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Anonymouse' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Anonymouse
  pod 'CryptoSwift', '0.7.1'
  pod 'Alamofire', '~> 4.2.0'
  pod 'SwiftyJSON', '4.0.0'

end

